# Generated by Django 4.2.1 on 2023-05-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
    ]
