# Generated by Django 4.2.1 on 2023-05-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("accounts", "0005_customuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="PointUser",
        ),
    ]
